# Generated by Django 2.2.10 on 2020-06-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0005_auto_20200611_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPkAndSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', editable=False, max_length=200)),
            ],
        ),
    ]
