# Generated by Django 2.2.10 on 2020-06-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200627_1856'),
    ]

