# Generated by Django 2.2.10 on 2020-06-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200627_1859'),
    ]

