# Generated by Django 2.2.10 on 2020-06-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_book_published_year'),
    ]

