# Generated by Django 2.2.10 on 2020-07-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_maark_returned', 'Set book as returned'),)},
        ),
    ]
